---
- name: Create nginx namespace
  shell: sudo kubectl create namespace nginx
  ignore_errors: yes

- name: Label nginx namespace
  shell: sudo kubectl label namespace/nginx run=nginx --overwrite

- name: Trigger nginx App deployment
  shell: sudo kubectl run nginx --image=nginx --port=8000 --image-pull-policy=Never -n nginx
  ignore_errors: yes

- name: Create Service for nginx App Deployment 
  shell: sudo kubectl expose deployment nginx --type=LoadBalancer --name=nginx -n nginx --external-ip=`sudo kubectl cluster-info | grep master | awk '{print $6}' | tr -d 'https//' | awk -F':' '{print $2}'` 
  ignore_errors: yes

