---
- include: ../../docker-eval/tasks/main.yml

- name: Create airports namespace
  shell: sudo kubectl create namespace airports 
  ignore_errors: yes

- name: Create NetworkPolciy
  shell: sudo kubectl create -f roles/deploy-air-ports/tasks/networkpolicy.yml -n airports
  ignore_errors: yes

- name: Trigger airports App deployment
  shell: sudo kubectl run airports-assembly --image=airports-assembly:1.0.1 --port=8080 --image-pull-policy=Never -n airports 
  ignore_errors: yes

- name: Create Service for airports App Deployment 
  shell: sudo kubectl expose deployment/airports-assembly -n airports
  ignore_errors: yes
