kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-nginx
spec:
  podSelector:
    matchLabels:
      run: airports-assembly
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          run: nginx
